name: 'CI Builds'
on: [push]
jobs:
  build-linux:
    strategy:
      matrix:
        dist:
          - debian.12
          - fedora.41
          - opensuse.tumbleweed
          - ubuntu.24.04
    runs-on: ubuntu-latest
    container: veyon/ci.linux.${{matrix.dist}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: .ci/linux.${{matrix.dist}}/script.sh $GITHUB_WORKSPACE /tmp
